name: Docker build

on: push


jobs:
  build:
    name: Docker build process
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      -
        name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: docker build
        run: docker build . --file ./Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/gh-action-img:latest
      - name: docker push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/gh-action-img:latest
